# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        r-version: [3.6, 4.0]
    steps:
      - uses: actions/checkout@v2
      - name: Install linux dependencies
        run: |
          sudo apt install libcurl4-openssl-dev -y
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "knitr", "covr", "xml2"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: R CMD check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
      - name: Code coverage
        run: covr::codecov(token = "${{ secrets.COVERALL_REPO_TOKEN }}")
        shell: Rscript {0}
